include:
  - ../frontend/docker-compose.yml
  - ../platform/docker-compose.yml
services:
  ci_tests:
    image: helium/ci-tests
    env_file: .env
    depends_on:
      - db
      - cache
      - storage
      - frontend
      - resource
      - api
      - worker
