test_name: Teardown

includes:
  - !include common.yaml

stages:
  - name: Get token for user
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/auth/token/"
      verify: false
      method: POST
      json:
        username: "{test_username:s}"
        password: "{test_password:s}"
    response:
      status_code: 200
      save:
        body:
          auth_token: token

  - name: Delete registered user
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/auth/user/delete/"
      verify: false
      method: DELETE
      headers:
        Authorization: "Token {auth_token:s}"
      json:
        username: "{test_username:s}"
        email: "{test_email:s}"
        password: "{test_password:s}"
    response:
      status_code: 204
