test_name: Setup

includes:
  - !include common.yaml

stages:
  - name: Cleanup workspace, if dirty
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/info/"
      method: GET
      verify: false
    response:
      save:
        $ext:
          function: utils.workspacehelper:init_workspace
          extra_kwargs:
            env_api_host: "{tavern.env_vars.PROJECT_API_HOST}"
            username: "{test_username:s}"
            email: "{test_email:s}"
            password: "{test_password:s}"

  - name: Register new user
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/auth/user/register/"
      verify: false
      method: POST
      json:
        username: "{test_username:s}"
        email: "{test_email:s}"
        password: "{test_password:s}"
        time_zone: America/Chicago
    response:
      status_code: 201

  - name: Get verification code from email
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/info/"
      method: GET
      verify: false
    response:
      save:
        $ext:
          function: utils.emailhelper:get_verification_code
          extra_kwargs:
            username: "{test_username:s}"

  - name: Verify user
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/auth/user/verify/?username={test_username:s}&code={email_verification_code}&welcome-email=false"
      verify: false
      method: GET
    response:
      status_code: 200

  - name: Get token for user
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/auth/token/"
      verify: false
      method: POST
      json:
        username: "{test_username:s}"
        password: "{test_password:s}"
    response:
      status_code: 200
      save:
        $ext:
          function: utils.workspacehelper:wait_for_example_schedule
          extra_kwargs:
            env_api_host: "{tavern.env_vars.PROJECT_API_HOST}"