test_name: Teardown and delete the user

marks:
  - usefixtures:
      - access_token

stages:
  - name: Delete user
    request:
      url: "{tavern.env_vars.PROJECT_API_HOST}/auth/user/delete/"
      verify: false
      method: DELETE
      headers:
        Authorization: "Bearer {access_token:s}"
      json:
        password: "{test_password:s}"
    response:
      status_code: 204