name: "CI Tests"

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 9 * * *"


jobs:
  build:
    name: Build

    env:
      CI_TWILIO_RECIPIENT_PHONE_NUMBER: ${{ secrets.CI_TWILIO_RECIPIENT_PHONE_NUMBER }}
      PLATFORM_AWS_S3_ACCESS_KEY_ID: ${{ secrets.PLATFORM_AWS_S3_ACCESS_KEY_ID }}
      PLATFORM_AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.PLATFORM_AWS_S3_SECRET_ACCESS_KEY }}
      PLATFORM_TWILIO_ACCOUNT_SID: ${{ secrets.PLATFORM_TWILIO_ACCOUNT_SID }}
      PLATFORM_TWILIO_AUTH_TOKEN: ${{ secrets.PLATFORM_TWILIO_AUTH_TOKEN }}
      PROJECT_API_HOST: $API_HOST
      PROJECT_APP_HOST: $APP_HOST

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Install dependencies
        run:
          make install
      - name: Run tests
        run:
          make test
