name: "CI Tests"

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request_target:
  schedule:
    - cron: "0 9 * * *"

concurrency:
  group: helium-singleton-ci-tests

jobs:
  ci:
    name: "CI Tests"

    env:
      PLATFORM_AWS_S3_ACCESS_KEY_ID: ${{ secrets.PLATFORM_AWS_S3_ACCESS_KEY_ID }}
      PLATFORM_AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.PLATFORM_AWS_S3_SECRET_ACCESS_KEY }}
      PLATFORM_TWILIO_ACCOUNT_SID: ${{ secrets.PLATFORM_TWILIO_ACCOUNT_SID }}
      PLATFORM_TWILIO_AUTH_TOKEN: ${{ secrets.PLATFORM_TWILIO_AUTH_TOKEN }}
      CI_TWILIO_RECIPIENT_PHONE_NUMBER: ${{ secrets.CI_TWILIO_RECIPIENT_PHONE_NUMBER }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Install dependencies
        run: make install
      - name: Run smoke tests
        if: ${{ github.event_name == 'pull_request' }}
        run: make test-smoke
      - name: Run full test suite
        if: ${{ github.event_name != 'pull_request' }}
        run: make test
